# Generated by Django 4.1.5 on 2023-01-25 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments_name', models.CharField(max_length=120)),
                ('assignment_description', models.CharField(max_length=12)),
                ('class_id', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField()),
                ('date_created', models.DateField(default=datetime.datetime(2023, 1, 24, 19, 32, 37, 363714))),
            ],
        ),
    ]
