# Generated by Django 4.1.5 on 2023-01-25 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 24, 19, 33, 26, 335298)),
        ),
    ]
