# Generated by Django 4.1.5 on 2023-01-25 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assignments_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 24, 19, 35, 15, 746035)),
        ),
    ]
