# Generated by Django 4.1.5 on 2023-01-31 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userclassdata_remove_classes_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=8)),
                ('assignment_id', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=20)),
                ('recieved_grade', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='assignments',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 30, 21, 6, 6, 228052)),
        ),
    ]
