# Generated by Django 4.1.5 on 2023-01-31 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userassignmentdata_alter_assignments_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 30, 21, 9, 11, 951805)),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
