# Generated by Django 4.1.5 on 2023-01-31 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_assignments_date_created_alter_assignments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 30, 21, 10, 48, 906594)),
        ),
        migrations.AlterField(
            model_name='userassignmentdata',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userassignmentdata',
            name='recieved_grade',
            field=models.IntegerField(null=True),
        ),
    ]
