# Generated by Django 4.1.5 on 2023-01-31 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_assignments_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 1, 30, 21, 39, 56, 113351)),
        ),
    ]
